# Generated by Django 3.2.4 on 2021-07-05 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_do', '0003_remove_newtweet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtweet',
            name='likes',
            field=models.ManyToManyField(related_name='like_tweet', to=settings.AUTH_USER_MODEL),
        ),
    ]
